#
# Module manifest for module 'Skyline.DataMiner.QAOps.PipelineLibrary'
#
# Generated by: JanS
#
# Generated on: 23/03/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Skyline.DataMiner.QAOps.PipelineLibrary.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'dd2034f4-c065-4d5a-8cbc-d8aec94f34b0'

# Author of this module
Author = 'JanS'

# Company or vendor of this module
CompanyName = 'Skyline Communications'

# Copyright statement for this module
Copyright = '(c) Skyline Communications. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Shared QAOps pipeline functions for DataMiner automation and test execution.'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Invoke-DotNetTestAndPublishResults',
    'Import-QAFrameworkTestMetadata',
    'Get-QAFrameworkRunConfiguration',
    'Get-QAFrameworkClusterTopology',
    'Select-QAFrameworkTest',
    'New-QAFrameworkExecutionPlan',
    'Publish-QAFrameworkTestResult',
    'Invoke-QAFrameworkTestRun',
    'Initialize-QAFrameworkAgents',
    'Invoke-QAFrameworkTestPackage',
    'Invoke-QAFrameworkTestDiscovery'
)

# Files packaged with this module.
FileList = @(
    'Skyline.DataMiner.QAOps.PipelineLibrary.psm1',
    'Skyline.DataMiner.QAOps.PipelineLibrary.psd1',
    'Private/ConvertFrom-QAFrameworkAttributeBlock.ps1',
    'Private/ConvertFrom-QAFrameworkAttributeValue.ps1',
    'Private/ConvertFrom-QAFrameworkMetaFile.ps1',
    'Private/ConvertTo-QAFrameworkTestMetadata.ps1',
    'Private/Copy-QAFrameworkDependency.ps1',
    'Private/Get-QAFrameworkAttribute.ps1',
    'Private/Get-QAFrameworkClassAttributeBlock.ps1',
    'Private/Get-QAFrameworkExecutionOutcome.ps1',
    'Private/Get-QAFrameworkMethodAttributeFlag.ps1',
    'Private/Invoke-QAFrameworkFailoverSwitch.ps1',
    'Private/Invoke-QAFrameworkLogCollection.ps1',
    'Private/Join-QAFrameworkAgentPath.ps1',
    'Private/Limit-String.ps1',
    'Private/New-QAFrameworkAutomationScriptXml.ps1',
    'Private/New-QAFrameworkExecutionCommand.ps1',
    'Private/New-QAFrameworkTestMetadata.ps1',
    'Private/Resolve-QAFrameworkTargetAgent.ps1',
    'Private/Select-QAFrameworkNextWorkItem.ps1',
    'Private/Split-QAFrameworkAttributeArgument.ps1',
    'Private/Test-QAFrameworkHarvestFilter.ps1',
    'Private/Test-QAFrameworkListMatch.ps1',
    'Private/Test-QAFrameworkPreRunFilter.ps1',
    'Private/Test-QAFrameworkSolutionCompatible.ps1',
    'Private/Test-QAFrameworkVersionCompatible.ps1',
    'Public/Get-QAFrameworkClusterTopology.ps1',
    'Public/Get-QAFrameworkRunConfiguration.ps1',
    'Public/Import-QAFrameworkTestMetadata.ps1',
    'Public/Initialize-QAFrameworkAgents.ps1',
    'Public/Invoke-DotNetTestAndPublishResults.ps1',
    'Public/Invoke-QAFrameworkTestDiscovery.ps1',
    'Public/Invoke-QAFrameworkTestPackage.ps1',
    'Public/Invoke-QAFrameworkTestRun.ps1',
    'Public/New-QAFrameworkExecutionPlan.ps1',
    'Public/Publish-QAFrameworkTestResult.ps1',
    'Public/Select-QAFrameworkTest.ps1',
    'Templates/1.TestPackageSetup.sample.ps1',
    'Templates/2.TestPackageExecution.sample.ps1',
    'Templates/3.TestPackageFinalize.sample.ps1',
    'Templates/Initialize-QAFrameworkAgent.ps1',
    'Templates/qaframework.config.sample.json',
    'Templates/qaframework.discovery.sample.json',
    'Templates/qaframework.tests.sample.json',
    'Templates/TestDiscovery.sample.ps1'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('DataMiner', 'QAOps', 'Pipeline', 'Testing', 'dotnet')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '0.1.0 - Added the QAFramework library: test discovery and harvesting, metadata import, run configuration, cluster topology, test selection, execution planning, the weight based scheduler with failover orchestration and result publishing. Every test runs through QAOps bridge executions, so a test package also works on a QAOps Bridge without DataMiner.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}